/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  TestIncentiveId,
  TestIncentiveIdInterface,
} from "../TestIncentiveId";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "contract IERC20Minimal",
            name: "rewardToken",
            type: "address",
          },
          {
            internalType: "contract IUniswapV3Pool",
            name: "pool",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "startTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "endTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "vestingPeriod",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "refundee",
            type: "address",
          },
        ],
        internalType: "struct IUniswapV3Staker.IncentiveKey",
        name: "key",
        type: "tuple",
      },
    ],
    name: "compute",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101c0806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80636d3b460014610030575b600080fd5b61004361003e36600461009a565b610059565b6040516100509190610125565b60405180910390f35b60006100648261006a565b92915050565b60008160405160200161007d919061012e565b604051602081830303815290604052805190602001209050919050565b600060c082840312156100ab578081fd5b60405160c0810181811067ffffffffffffffff821117156100c857fe5b60405282356100d68161018e565b815260208301356100e68161018e565b8060208301525060408301356040820152606083013560608201526080830135608082015260a08301356101198161018e565b60a08201529392505050565b90815260200190565b600060c08201905073ffffffffffffffffffffffffffffffffffffffff8084511683528060208501511660208401526040840151604084015260608401516060840152608084015160808401528060a08501511660a08401525092915050565b73ffffffffffffffffffffffffffffffffffffffff811681146101b057600080fd5b5056fea164736f6c6343000706000a";

export class TestIncentiveId__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<TestIncentiveId> {
    return super.deploy(overrides || {}) as Promise<TestIncentiveId>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): TestIncentiveId {
    return super.attach(address) as TestIncentiveId;
  }
  connect(signer: Signer): TestIncentiveId__factory {
    return super.connect(signer) as TestIncentiveId__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TestIncentiveIdInterface {
    return new utils.Interface(_abi) as TestIncentiveIdInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TestIncentiveId {
    return new Contract(address, _abi, signerOrProvider) as TestIncentiveId;
  }
}
